// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjektZespołówka.Data;

#nullable disable

namespace ProjektZespołówka.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260118211731_Inital")]
    partial class Inital
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjektZespołówka.Models.Addons", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("EntityId")
                        .HasColumnType("int")
                        .HasColumnName("encja_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("typ_encji");

                    b.Property<Guid>("FileAttachmentId")
                        .HasMaxLength(500)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("plik_url");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_dodania");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("dodane_przez");

                    b.HasKey("Id");

                    b.ToTable("Załączniki", (string)null);
                });

            modelBuilder.Entity("ProjektZespołówka.Models.Comments", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("autor_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("treść");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_dodania");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("encja_id");

                    b.Property<int>("EntityType")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("typ_encji");

                    b.Property<int>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("Uwagi", (string)null);
                });

            modelBuilder.Entity("ProjektZespołówka.Models.ExecutiveDocuments", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("DocumentId")
                        .HasMaxLength(500)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("plik_pdf_url");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("projekt_id");

                    b.Property<Guid>("RecipientId")
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("odbiorca");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_wygenerowania");

                    b.HasKey("Id");

                    b.ToTable("Dokumenty_wykonawcze", (string)null);
                });

            modelBuilder.Entity("ProjektZespołówka.Models.Levels", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CableType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("kat_rodzajKabla");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_dodania");

                    b.Property<int>("LevelNumber")
                        .HasColumnType("int")
                        .HasColumnName("numer");

                    b.Property<string>("LevelPlanFileAttachmentId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("plik_rzutu_url");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("projekt_id");

                    b.Property<string>("TechnicalDescription")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("oznaczenie_techniczne");

                    b.HasKey("Id");

                    b.ToTable("Poziomy", (string)null);
                });

            modelBuilder.Entity("ProjektZespołówka.Models.Localization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("dane_adresowe");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("dane_kontaktowe");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("contact_phone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("opis");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nazwa");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_utworzenia");

                    b.HasKey("Id");

                    b.ToTable("Lokalizacje", (string)null);
                });

            modelBuilder.Entity("ProjektZespołówka.Models.Measurments", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AttachmentId")
                        .HasMaxLength(500)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("plik_raportu_url");

                    b.Property<int>("Certification")
                        .HasMaxLength(20)
                        .HasColumnType("int")
                        .HasColumnName("status_certyfikacji");

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_pomiaru");

                    b.Property<Guid>("OutletId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("gniazdo_id");

                    b.Property<Guid>("ServiceWorkerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("serwisant_id");

                    b.Property<string>("TechnicalDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("parametry_techniczne");

                    b.Property<int>("Type")
                        .HasMaxLength(30)
                        .HasColumnType("int")
                        .HasColumnName("wynik_pomiaru");

                    b.HasKey("Id");

                    b.ToTable("Pomiary", (string)null);
                });

            modelBuilder.Entity("ProjektZespołówka.Models.NetworkRack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("FrontViewImageId")
                        .HasMaxLength(500)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("zdjęcie_przód_url");

                    b.Property<DateTime>("InstallationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_montażu");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lokalizacja");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("model");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("projekt_id");

                    b.Property<Guid>("RearViewImageId")
                        .HasMaxLength(500)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("zdjęcie_tył_url");

                    b.Property<Guid>("SideViewImageId")
                        .HasMaxLength(500)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("zdjęcie_bok_url");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("rozmiar");

                    b.HasKey("Id");

                    b.ToTable("Szafy_sieciowe", (string)null);
                });

            modelBuilder.Entity("ProjektZespołówka.Models.Outlet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("FarPhotoId")
                        .HasMaxLength(500)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("zdjęcie_odległość_url");

                    b.Property<DateTime>("InstallationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_instalacji");

                    b.Property<Guid>("NearPhotoId")
                        .HasMaxLength(500)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("zdjęcie_zbiżenie_url");

                    b.Property<int>("OutletCount")
                        .HasColumnType("int")
                        .HasColumnName("liczba_gniazd");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("pomieszczenie_id");

                    b.Property<Guid>("ServedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("serwisant_id");

                    b.Property<int>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("TechnicalName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("oznaczenie_techniczne");

                    b.Property<int>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("int")
                        .HasColumnName("typ_gniazda");

                    b.HasKey("Id");

                    b.HasIndex("TechnicalName")
                        .IsUnique();

                    b.ToTable("Gniazda", (string)null);
                });

            modelBuilder.Entity("ProjektZespołówka.Models.OutletStages", b =>
                {
                    b.Property<Guid>("WorkStageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("etap_id");

                    b.Property<Guid>("OutletId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("gniazdo_id");

                    b.HasKey("WorkStageId", "OutletId");

                    b.ToTable("Etapy_gniazda", (string)null);
                });

            modelBuilder.Entity("ProjektZespołówka.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("dane_kontaktowe");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("dane_adresowe");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_utworzenia");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("opis");

                    b.Property<Guid>("InvestorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("inwestor_id");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("lokalizacja_id");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("kierownik_id");

                    b.Property<int>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("int")
                        .HasColumnName("status_projektu");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nazwa");

                    b.HasKey("Id");

                    b.ToTable("Projekty", (string)null);
                });

            modelBuilder.Entity("ProjektZespołówka.Models.RackPanel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("NetworkRackId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("szafa_id");

                    b.Property<int>("PortNumber")
                        .HasColumnType("int")
                        .HasColumnName("liczba_portów");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("pozycja");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("typ");

                    b.HasKey("Id");

                    b.ToTable("Panele_szaf", (string)null);
                });

            modelBuilder.Entity("ProjektZespołówka.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CoordinatesOnPlan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("współrzędne_na_rzucie");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("opis");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("pietro_id");

                    b.Property<int>("Number")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("nr_pomieszczenia");

                    b.Property<int>("OutletCount")
                        .HasColumnType("int");

                    b.Property<string>("TechnicalCode")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("oznaczenie_techniczne");

                    b.Property<string>("TechnicalName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nazwa_pomieszczenia");

                    b.HasKey("Id");

                    b.ToTable("Pomieszczenia", (string)null);
                });

            modelBuilder.Entity("ProjektZespołówka.Models.RoomStages", b =>
                {
                    b.Property<Guid>("WorkStageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("etap_id");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("pomieszczenie_id");

                    b.HasKey("WorkStageId", "RoomId");

                    b.ToTable("Etapy_pomieszczenia", (string)null);
                });

            modelBuilder.Entity("ProjektZespołówka.Models.ServiceWorkerInProject", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("projekt_id");

                    b.Property<Guid>("ServiceWorkerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("serwisant_id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_przypisania");

                    b.HasKey("ProjectId", "ServiceWorkerId");

                    b.ToTable("Serwisanci_w_projektach", (string)null);
                });

            modelBuilder.Entity("ProjektZespołówka.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name_Surname")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("imię_nazwisko");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_rejestracji");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("hasło");

                    b.Property<int>("role")
                        .HasMaxLength(20)
                        .HasColumnType("int")
                        .HasColumnName("rola");

                    b.HasKey("Id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("Użytkownicy", (string)null);
                });

            modelBuilder.Entity("ProjektZespołówka.Models.WorkStages", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AssignedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("przypisany_do");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_zakończenia");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2")
                        .HasColumnName("termin");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("opis");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("projekt_id");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nazwa");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_rozpoczęcia");

                    b.Property<int>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("Etapy_prac", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
